import type {
  SopAuditRecord,
  SopDocumentRecord,
  SopMasterRecord,
  SopReportRecord,
  SopWorkflowConfigurationRecord,
  SopWorkflowStageRecord,
  SopVersionRecord,
  SopWorkflowTask,
} from "./types";
import { normalizeStructuredContentForLevel } from "./structuredContent";

export const sopDocuments: SopDocumentRecord[] = [
  {
    id: "sop-001",
    sopNumber: "QA-L2-001",
    title: "Batch Record Review Process",
    subject: "Quality batch dossier review and release readiness",
    level: "Level 2",
    category: "Process Instructions",
    division: "Pharma Operations",
    department: "Quality Assurance",
    owner: "Riya Shah",
    checker: "Manan Patel",
    approver: "Neha Desai",
    authorizer: "Amit Rao",
    status: "Checker Review",
    version: "R2",
    draftCode: "D3",
    effectiveDate: "2026-06-15",
    reviewDate: "2027-06-15",
    createdAt: "2026-05-01T09:15:00",
    updatedAt: "2026-06-03T18:20:00",
    keywords: ["batch", "review", "qa", "release"],
    changeSummary: "Added deviation linkage and second-check verification notes.",
    priority: "Critical",
    pendingSinceDays: 2,
    trainingRequired: true,
    acknowledgementsPending: 14,
    viewersToday: 8,
    secureViewCount: 28,
    distributionCount: 3,
    purpose: "Ensure batch records are reviewed consistently before final disposition.",
    scope: "Applicable to all commercial product batches handled by QA reviewers.",
    workflowLabel: "Draft -> Checker -> Approver -> Authorizer -> Release",
    structuredContent: normalizeStructuredContentForLevel({
      level: "Level 2",
      title: "Batch Record Review Process",
      department: "Quality Assurance",
      purpose: "Ensure batch records are reviewed consistently before final disposition.",
      scope: "Applicable to all commercial product batches handled by QA reviewers.",
    }),
    contentSource: "editor",
    contentFileName: null,
    contentFileUrl: null,
    currentReleasedVersion: "R1",
  },
  {
    id: "sop-002",
    sopNumber: "ENG-L3-014",
    title: "Granulation Machine Start-up",
    subject: "Safe machine start-up and pre-run checks",
    level: "Level 3",
    category: "Work Instructions",
    division: "Manufacturing",
    department: "Production",
    owner: "Dhruv Mehta",
    checker: "Krupa Shah",
    approver: "Viral Soni",
    authorizer: "Amit Rao",
    status: "Released",
    version: "R1",
    draftCode: "D1",
    effectiveDate: "2026-04-10",
    reviewDate: "2027-04-10",
    createdAt: "2026-03-01T08:00:00",
    updatedAt: "2026-04-10T10:30:00",
    keywords: ["machine", "startup", "safety", "granulation"],
    changeSummary: "Major revision aligned with new PLC interlock validation.",
    priority: "High",
    pendingSinceDays: 0,
    trainingRequired: true,
    acknowledgementsPending: 4,
    viewersToday: 23,
    secureViewCount: 61,
    distributionCount: 5,
    purpose: "Guide operators through validated start-up steps for the granulation machine.",
    scope: "Applies to production lines G-07 and G-08.",
    workflowLabel: "Controlled copy released to Production and QA.",
    structuredContent: normalizeStructuredContentForLevel({
      level: "Level 3",
      title: "Granulation Machine Start-up",
      department: "Production",
      purpose: "Guide operators through validated start-up steps for the granulation machine.",
      scope: "Applies to production lines G-07 and G-08.",
    }),
    contentSource: "editor",
    contentFileName: null,
    contentFileUrl: null,
    currentReleasedVersion: "R1",
  },
  {
    id: "sop-003",
    sopNumber: "WH-L2-008",
    title: "Raw Material Quarantine Release",
    subject: "Warehouse release after QA clearance",
    level: "Level 2",
    category: "Process Instructions",
    division: "Supply Chain",
    department: "Warehouse",
    owner: "Parth Joshi",
    checker: "Riya Shah",
    approver: "Neha Desai",
    authorizer: "Amit Rao",
    status: "Approver Review",
    version: "R2",
    draftCode: "D2",
    effectiveDate: "2026-06-21",
    reviewDate: "2027-06-21",
    createdAt: "2026-05-11T11:30:00",
    updatedAt: "2026-06-02T15:45:00",
    keywords: ["warehouse", "quarantine", "release"],
    changeSummary: "Updated quarantine tag verification and ERP status step.",
    priority: "High",
    pendingSinceDays: 5,
    trainingRequired: false,
    acknowledgementsPending: 0,
    viewersToday: 2,
    secureViewCount: 12,
    distributionCount: 2,
    purpose: "Control movement of quarantined raw materials after QA approval.",
    scope: "All incoming raw materials under warehouse quarantine.",
    workflowLabel: "Approval pending before final authorization.",
    structuredContent: normalizeStructuredContentForLevel({
      level: "Level 2",
      title: "Raw Material Quarantine Release",
      department: "Warehouse",
      purpose: "Control movement of quarantined raw materials after QA approval.",
      scope: "All incoming raw materials under warehouse quarantine.",
    }),
    contentSource: "editor",
    contentFileName: null,
    contentFileUrl: null,
    currentReleasedVersion: "R1",
  },
  {
    id: "sop-004",
    sopNumber: "QC-L3-022",
    title: "HPLC Calibration Sequence",
    subject: "Calibration and sequence preparation for QC instruments",
    level: "Level 3",
    category: "Work Instructions",
    division: "Quality Control",
    department: "QC Lab",
    owner: "Nidhi Parmar",
    checker: "Rakesh Trivedi",
    approver: "Neha Desai",
    authorizer: "Amit Rao",
    status: "Authorizer Review",
    version: "R2",
    draftCode: "D4",
    effectiveDate: "2026-06-12",
    reviewDate: "2027-06-12",
    createdAt: "2026-05-18T10:10:00",
    updatedAt: "2026-06-04T09:05:00",
    keywords: ["hplc", "calibration", "qc", "sequence"],
    changeSummary: "Included SST acceptance criteria and second analyst verification.",
    priority: "Critical",
    pendingSinceDays: 1,
    trainingRequired: true,
    acknowledgementsPending: 11,
    viewersToday: 4,
    secureViewCount: 18,
    distributionCount: 2,
    purpose: "Ensure reproducible calibration and sequence configuration in QC analysis.",
    scope: "Applicable to all HPLC systems in QC lab.",
    workflowLabel: "Final authorization stage before release.",
    structuredContent: normalizeStructuredContentForLevel({
      level: "Level 3",
      title: "HPLC Calibration Sequence",
      department: "QC Lab",
      purpose: "Ensure reproducible calibration and sequence configuration in QC analysis.",
      scope: "Applicable to all HPLC systems in QC lab.",
    }),
    contentSource: "editor",
    contentFileName: null,
    contentFileUrl: null,
    currentReleasedVersion: "R1",
  },
  {
    id: "sop-005",
    sopNumber: "HR-L2-003",
    title: "New Employee GxP Induction",
    subject: "Training induction and controlled acknowledgement process",
    level: "Level 2",
    category: "Process Instructions",
    division: "Corporate Services",
    department: "Human Resources",
    owner: "Heena Modi",
    checker: "Priyesh Shah",
    approver: "Viral Soni",
    authorizer: "Amit Rao",
    status: "Draft",
    version: "R0",
    draftCode: "D1",
    effectiveDate: "2026-07-01",
    reviewDate: "2027-07-01",
    createdAt: "2026-06-01T14:00:00",
    updatedAt: "2026-06-04T12:40:00",
    keywords: ["training", "induction", "gxp"],
    changeSummary: "Initial draft prepared for onboarding compliance.",
    priority: "Medium",
    pendingSinceDays: 0,
    trainingRequired: true,
    acknowledgementsPending: 0,
    viewersToday: 0,
    secureViewCount: 0,
    distributionCount: 0,
    purpose: "Standardize induction for new joiners working in GxP areas.",
    scope: "All new employees and contractual staff.",
    workflowLabel: "Draft under preparation by HR.",
    structuredContent: normalizeStructuredContentForLevel({
      level: "Level 2",
      title: "New Employee GxP Induction",
      department: "Human Resources",
      purpose: "Standardize induction for new joiners working in GxP areas.",
      scope: "All new employees and contractual staff.",
    }),
    contentSource: "editor",
    contentFileName: null,
    contentFileUrl: null,
    currentReleasedVersion: null,
  },
  {
    id: "sop-006",
    sopNumber: "IT-L2-019",
    title: "User Access Review",
    subject: "Periodic access review for regulated systems",
    level: "Level 2",
    category: "Process Instructions",
    division: "Digital Systems",
    department: "IT Compliance",
    owner: "Jay Vora",
    checker: "Manan Patel",
    approver: "Neha Desai",
    authorizer: "Amit Rao",
    status: "Archived",
    version: "R1",
    draftCode: "D2",
    effectiveDate: "2025-12-18",
    reviewDate: "2026-12-18",
    createdAt: "2025-10-01T09:00:00",
    updatedAt: "2026-05-20T16:15:00",
    keywords: ["access", "review", "it", "compliance"],
    changeSummary: "Superseded by consolidated access governance procedure.",
    priority: "Low",
    pendingSinceDays: 0,
    trainingRequired: false,
    acknowledgementsPending: 0,
    viewersToday: 0,
    secureViewCount: 2,
    distributionCount: 1,
    purpose: "Maintain periodic access review evidence for critical systems.",
    scope: "ERP, LMS, QMS and analytical systems.",
    workflowLabel: "Archived after merger into new SOP family.",
    structuredContent: normalizeStructuredContentForLevel({
      level: "Level 2",
      title: "User Access Review",
      department: "IT Compliance",
      purpose: "Maintain periodic access review evidence for critical systems.",
      scope: "ERP, LMS, QMS and analytical systems.",
    }),
    contentSource: "editor",
    contentFileName: null,
    contentFileUrl: null,
    currentReleasedVersion: "R1",
  },
];

export const sopVersions: SopVersionRecord[] = [
  {
    id: "v-001",
    sopId: "sop-001",
    version: "R2",
    stage: "Checker Review",
    revisionDate: "2026-06-03",
    revisedBy: "Riya Shah",
    changeSummary: "Deviation checklist added before QA release.",
    approvalTrail: "Creator complete, checker pending.",
  },
  {
    id: "v-002",
    sopId: "sop-001",
    version: "R1",
    stage: "Released",
    revisionDate: "2025-12-14",
    revisedBy: "Riya Shah",
    changeSummary: "Major release for new product family.",
    releaseDate: "2025-12-20",
    approvalTrail: "Approved by Neha Desai, authorized by Amit Rao.",
  },
  {
    id: "v-003",
    sopId: "sop-002",
    version: "R1",
    stage: "Released",
    revisionDate: "2026-04-10",
    revisedBy: "Dhruv Mehta",
    changeSummary: "PLC interlocks included in machine checks.",
    releaseDate: "2026-04-10",
    approvalTrail: "Released to Production after final authorization.",
  },
  {
    id: "v-004",
    sopId: "sop-004",
    version: "R2",
    stage: "Authorizer Review",
    revisionDate: "2026-06-04",
    revisedBy: "Nidhi Parmar",
    changeSummary: "System suitability guidance updated.",
    approvalTrail: "Awaiting authorizer sign-off.",
  },
  {
    id: "v-005",
    sopId: "sop-006",
    version: "R1",
    stage: "Archived",
    revisionDate: "2026-05-20",
    revisedBy: "Jay Vora",
    changeSummary: "Archived after process consolidation.",
    releaseDate: "2025-12-18",
    approvalTrail: "Historical record retained for audit.",
  },
];

export const sopWorkflowTasks: SopWorkflowTask[] = [
  {
    id: "task-001",
    sopId: "sop-001",
    sopNumber: "QA-L2-001",
    title: "Batch Record Review Process",
    assignedTo: "Manan Patel",
    role: "Checker",
    stage: "Checker Review",
    dueDate: "2026-06-05",
    ageDays: 2,
    slaStatus: "Due Today",
    comments: "Verify deviation annexure and CAPA linkage.",
    availableActions: ["Approve", "Return"],
  },
  {
    id: "task-002",
    sopId: "sop-003",
    sopNumber: "WH-L2-008",
    title: "Raw Material Quarantine Release",
    assignedTo: "Neha Desai",
    role: "Approver",
    stage: "Approver Review",
    dueDate: "2026-06-04",
    ageDays: 5,
    slaStatus: "Breached",
    comments: "Waiting for warehouse exception note attachment.",
    availableActions: ["Approve", "Return"],
  },
  {
    id: "task-003",
    sopId: "sop-004",
    sopNumber: "QC-L3-022",
    title: "HPLC Calibration Sequence",
    assignedTo: "Amit Rao",
    role: "Authorizer",
    stage: "Authorizer Review",
    dueDate: "2026-06-06",
    ageDays: 1,
    slaStatus: "On Track",
    comments: "Critical release for chromatography systems.",
    availableActions: ["Authorize", "Return"],
  },
  {
    id: "task-004",
    sopId: "sop-005",
    sopNumber: "HR-L2-003",
    title: "New Employee GxP Induction",
    assignedTo: "Heena Modi",
    role: "Creator",
    stage: "Draft",
    dueDate: "2026-06-08",
    ageDays: 0,
    slaStatus: "On Track",
    comments: "Attach induction checklist template before submit.",
    availableActions: ["Submit", "Archive"],
  },
];

export const sopAuditRecords: SopAuditRecord[] = [
  {
    id: "audit-001",
    timestamp: "2026-06-04 12:30",
    user: "Nidhi Parmar",
    role: "Creator",
    action: "Submitted",
    module: "SOP Workflow",
    sopNumber: "QC-L3-022",
    oldValue: "Stage: Approver Review",
    newValue: "Stage: Authorizer Review",
    ipAddress: "10.10.4.18",
    device: "QC-LAB-TERM-02",
  },
  {
    id: "audit-002",
    timestamp: "2026-06-04 09:18",
    user: "Asha Clerk",
    role: "Department User",
    action: "Viewed",
    module: "Secure Viewer",
    sopNumber: "ENG-L3-014",
    oldValue: "Viewer closed",
    newValue: "Page 3 opened with watermark",
    ipAddress: "10.10.2.44",
    device: "PRD-TAB-19",
  },
  {
    id: "audit-003",
    timestamp: "2026-06-03 18:20",
    user: "Riya Shah",
    role: "Creator",
    action: "Created",
    module: "SOP Authoring",
    sopNumber: "QA-L2-001",
    oldValue: "Version R1",
    newValue: "Version R2 draft",
    ipAddress: "10.10.1.22",
    device: "QA-MGR-07",
  },
  {
    id: "audit-004",
    timestamp: "2026-06-03 18:22",
    user: "Riya Shah",
    role: "Creator",
    action: "Downloaded Attempt",
    module: "Secure Viewer",
    sopNumber: "QA-L2-001",
    oldValue: "Download blocked",
    newValue: "Attempt logged and denied",
    ipAddress: "10.10.1.22",
    device: "QA-MGR-07",
  },
  {
    id: "audit-005",
    timestamp: "2026-06-02 15:45",
    user: "Neha Desai",
    role: "Approver",
    action: "Returned",
    module: "SOP Workflow",
    sopNumber: "WH-L2-008",
    oldValue: "Comments empty",
    newValue: "Need warehouse exception note",
    ipAddress: "10.10.5.11",
    device: "QA-HOD-03",
  },
];

export const sopReportRecords: SopReportRecord[] = [
  {
    id: "report-001",
    reportName: "SOP Register",
    description: "Master register with version, owner and lifecycle stage.",
    frequency: "Daily",
    owner: "QA Systems",
    lastGenerated: "2026-06-04 08:00",
    format: "XLSX",
    status: "Ready",
  },
  {
    id: "report-002",
    reportName: "Pending Approvals",
    description: "Open checker, approver and authorizer queue by department.",
    frequency: "Hourly",
    owner: "Compliance Cell",
    lastGenerated: "2026-06-04 12:00",
    format: "PDF",
    status: "Ready",
  },
  {
    id: "report-003",
    reportName: "Revision History",
    description: "Historical change summary and superseded version traceability.",
    frequency: "Weekly",
    owner: "Document Control",
    lastGenerated: "2026-06-03 19:10",
    format: "CSV",
    status: "Needs Review",
  },
  {
    id: "report-004",
    reportName: "Expired SOP Report",
    description: "SOPs due for revision within next 30 days.",
    frequency: "Weekly",
    owner: "QA Systems",
    lastGenerated: "2026-06-02 09:30",
    format: "PDF",
    status: "Scheduled",
  },
];

export const sopMasterRecords: SopMasterRecord[] = [
  {
    id: "master-001",
    type: "Company",
    name: "TechElecon Pvt Ltd",
    code: "TECH",
    owner: "Admin",
    status: "Active",
    updatedAt: "2026-05-20",
    notes: "Parent company configuration root.",
  },
  {
    id: "master-002",
    type: "Division",
    name: "Pharma Operations",
    code: "PHOPS",
    owner: "Document Control",
    status: "Active",
    updatedAt: "2026-05-30",
    notes: "Mapped to Quality and Production departments.",
  },
  {
    id: "master-003",
    type: "Department",
    name: "Quality Assurance",
    code: "QA",
    owner: "Riya Shah",
    status: "Active",
    updatedAt: "2026-06-01",
    notes: "Primary owner for batch release SOPs.",
  },
  {
    id: "master-004",
    type: "Category",
    name: "SOP Level 2 - Process Instructions",
    code: "L2",
    owner: "Admin",
    status: "Active",
    updatedAt: "2026-05-10",
    contentHeaders: [
      "Purpose",
      "Scope",
      "Roles and Responsibilities",
      "Procedure",
      "Annexure",
    ],
    notes: "Structured metadata enabled.",
  },
  {
    id: "master-005",
    type: "Workflow",
    name: "Regulated 4-Step Review",
    code: "WF-REG-01",
    owner: "QA Systems",
    status: "Active",
    updatedAt: "2026-05-28",
    notes: "Creator, checker, approver, authorizer sequence.",
  },
  {
    id: "master-006",
    type: "Role",
    name: "SOP Authorizer",
    code: "ROLE-AUTH",
    owner: "Security Admin",
    status: "Draft",
    updatedAt: "2026-06-03",
    notes: "Pending update with e-sign readiness.",
  },
];

export const sopStageCounts = [
  { key: "Draft", label: "Draft", value: 7, color: "#64748B" },
  { key: "Checker Review", label: "Checker Review", value: 4, color: "#2563EB" },
  { key: "Approver Review", label: "Approver Review", value: 3, color: "#D97706" },
  { key: "Authorizer Review", label: "Authorizer Review", value: 2, color: "#8B5CF6" },
  { key: "Released", label: "Released", value: 29, color: "#059669" },
  { key: "Archived", label: "Archived", value: 6, color: "#475569" },
];

export const sopDepartmentAdoption = [
  { department: "Quality Assurance", released: 8, pending: 2 },
  { department: "Production", released: 7, pending: 3 },
  { department: "Warehouse", released: 4, pending: 1 },
  { department: "QC Lab", released: 5, pending: 2 },
  { department: "IT Compliance", released: 3, pending: 1 },
];

export const sopSecurityHighlights = [
  "Secure PDF viewer with watermark and session lock",
  "Download, print, right-click and copy controls blocked",
  "Historical versions limited to authorized users",
  "IP and device activity logged for every sensitive event",
];


export const sopWorkflowConfigurations: SopWorkflowConfigurationRecord[] = [
  {
    id: "wf-config-001",
    scopeCompany: "TechElecon Pvt Ltd",
    scopeDivision: "Pharma Operations",
    scopeDepartment: "Quality Assurance",
    creatorRole: "SOP Creator",
    checkerRole: "SOP Checker",
    approverRole: "SOP Approver",
    authorizerRole: "SOP Authorizer",
    escalationRole: "Compliance Head",
    activeStatus: "Active",
    reminderFrequency: "Every 24 hours",
    auditRequired: true,
  },
];

export const sopWorkflowStages: SopWorkflowStageRecord[] = [
  {
    id: "wf-stage-001",
    stageName: "Draft",
    sequence: 1,
    roleResponsible: "SOP Creator",
    dueDays: 0,
    escalationAfterDays: 0,
    availableActions: ["Save Draft", "Submit"],
  },
  {
    id: "wf-stage-002",
    stageName: "Checker Review",
    sequence: 2,
    roleResponsible: "SOP Checker",
    dueDays: 2,
    escalationAfterDays: 3,
    availableActions: ["Approve", "Return"],
  },
  {
    id: "wf-stage-003",
    stageName: "Approver Review",
    sequence: 3,
    roleResponsible: "SOP Approver",
    dueDays: 2,
    escalationAfterDays: 3,
    availableActions: ["Approve", "Return"],
  },
  {
    id: "wf-stage-004",
    stageName: "Authorizer Review",
    sequence: 4,
    roleResponsible: "SOP Authorizer",
    dueDays: 1,
    escalationAfterDays: 2,
    availableActions: ["Authorize", "Return"],
  },
  {
    id: "wf-stage-005",
    stageName: "Release",
    sequence: 5,
    roleResponsible: "System / Authorizer",
    dueDays: 0,
    escalationAfterDays: 0,
    availableActions: ["Release", "Archive"],
  },
];
